# Generated by Django 4.1.4 on 2022-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_statuses_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='имя'),
        ),
    ]
