# Generated by Django 4.1.4 on 2023-01-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasklabel_task'),
        ('statuses', '0002_alter_statuses_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Status',
        ),
    ]
