# Generated by Django 4.1.4 on 2023-01-05 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0003_rename_labels_label'),
        ('statuses', '0003_rename_statuses_status'),
        ('tasks', '0003_alter_tasklabel_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
