# Generated by Django 4.1.4 on 2023-01-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_rename_labels_label'),
        ('tasks', '0005_alter_task_labels_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabel',
            name='label',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='labels.label'),
        ),
    ]
