# Generated by Django 4.1.4 on 2023-01-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasklabel_task'),
        ('labels', '0002_alter_labels_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
